'use client';
import { useEffect, useRef } from 'react';
import * as THREE from 'three';

export default function InnovationVillage(){
 const mount=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!mount.current)return;const host=mount.current;const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x030813,.035);const camera=new THREE.PerspectiveCamera(42,host.clientWidth/host.clientHeight,.1,100);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(host.clientWidth,host.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;host.appendChild(renderer.domElement);
 const world=new THREE.Group();scene.add(world);const glass=(color:number,opacity=.72)=>new THREE.MeshPhysicalMaterial({color,roughness:.2,metalness:.35,transparent:true,opacity,transmission:.18,emissive:color,emissiveIntensity:.15});const dark=new THREE.MeshStandardMaterial({color:0x071322,roughness:.34,metalness:.75});const cyan=new THREE.MeshStandardMaterial({color:0x44bfff,emissive:0x167bd8,emissiveIntensity:2});const violet=new THREE.MeshStandardMaterial({color:0x6d5fff,emissive:0x3928d8,emissiveIntensity:1.8});
 const base=new THREE.Mesh(new THREE.CylinderGeometry(10.5,11,1,6),dark);base.scale.z=.84;base.position.y=-.55;world.add(base);const grid=new THREE.GridHelper(22,22,0x255a8a,0x112c48);grid.position.y=.02;world.add(grid);
 const addBuilding=(x:number,z:number,h:number,w:number,color:number)=>{const g=new THREE.Group();const podium=new THREE.Mesh(new THREE.BoxGeometry(w+1,.35,w+1),dark);podium.position.y=.18;g.add(podium);const tower=new THREE.Mesh(new THREE.BoxGeometry(w,h,w),glass(color));tower.position.y=h/2+.38;g.add(tower);const cap=new THREE.Mesh(new THREE.BoxGeometry(w*.62,.18,w*.62),color===0x755cff?violet:cyan);cap.position.y=h+.48;g.add(cap);g.position.set(x,0,z);world.add(g);return g};
 addBuilding(-4,-2,3.6,2.3,0x2b8fff);addBuilding(0,-.5,5.2,2.5,0x3b9fff);addBuilding(4,2,3.2,2.1,0x755cff);addBuilding(-2.5,3.7,2.2,1.7,0x49c8ff);addBuilding(3.3,-3.5,2.6,1.8,0x606cff);
 for(let i=0;i<12;i++){const a=i/12*Math.PI*2;const cube=new THREE.Mesh(new THREE.BoxGeometry(.45,.45,.45),i%3===0?violet:cyan);cube.position.set(Math.cos(a)*7,.45+Math.sin(i)*.18,Math.sin(a)*5.5);world.add(cube)}
 const ring=new THREE.Mesh(new THREE.TorusGeometry(2.2,.07,12,80),cyan);ring.rotation.x=Math.PI/2;ring.position.set(0,.12,-.5);world.add(ring);const orb=new THREE.Mesh(new THREE.IcosahedronGeometry(.85,2),glass(0x6a78ff,.8));orb.position.set(0,6.6,-.5);world.add(orb);const orbWire=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.IcosahedronGeometry(1.25,2)),new THREE.LineBasicMaterial({color:0x56baff,transparent:true,opacity:.6}));orbWire.position.copy(orb.position);world.add(orbWire);
 const curveMat=new THREE.LineBasicMaterial({color:0x45b8ff,transparent:true,opacity:.72});[[-4,-2,0,-.5],[0,-.5,4,2],[0,-.5,-2.5,3.7],[0,-.5,3.3,-3.5]].forEach(p=>{const c=new THREE.CatmullRomCurve3([new THREE.Vector3(p[0],.35,p[1]),new THREE.Vector3((p[0]+p[2])/2,1.1,(p[1]+p[3])/2),new THREE.Vector3(p[2],.35,p[3])]);world.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(c.getPoints(40)),curveMat))});
 scene.add(new THREE.HemisphereLight(0x69bfff,0x02040a,1.35));const key=new THREE.PointLight(0x4faeff,48,32);key.position.set(-7,10,7);scene.add(key);const fill=new THREE.PointLight(0x705cff,35,28);fill.position.set(8,6,-7);scene.add(fill);camera.position.set(17,12,17);camera.lookAt(0,1.8,0);
 let mx=0,my=0,raf=0;const pointer=(e:PointerEvent)=>{mx=(e.clientX/innerWidth-.5);my=(e.clientY/innerHeight-.5)};const resize=()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)};addEventListener('pointermove',pointer);addEventListener('resize',resize);
 const animate=()=>{const parent=host.closest('.village-journey') as HTMLElement;const r=parent?.getBoundingClientRect();const travel=Math.max(1,(parent?.offsetHeight||innerHeight)-innerHeight);const p=Math.max(0,Math.min(1,-(r?.top||0)/travel));const angle=.65+p*Math.PI*2.05+mx*.12;const radius=18-p*6;camera.position.x=Math.cos(angle)*radius;camera.position.z=Math.sin(angle)*radius;camera.position.y=11-p*3-my*.5;camera.lookAt(0,1.7+p*1.2,0);world.rotation.y=p*.2;orb.rotation.y+=.004;orbWire.rotation.y-=.002;ring.rotation.z+=.002;renderer.render(scene,camera);raf=requestAnimationFrame(animate)};animate();return()=>{cancelAnimationFrame(raf);removeEventListener('pointermove',pointer);removeEventListener('resize',resize);renderer.dispose();host.removeChild(renderer.domElement)}},[]);
 return <div className="village-canvas" ref={mount} aria-hidden="true"/>;
}
