'use client';
import { useEffect, useRef } from 'react';
import * as THREE from 'three';

export default function InnovationVillage(){
 const mount=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!mount.current)return;const host=mount.current,scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x020711,.023);const camera=new THREE.PerspectiveCamera(38,host.clientWidth/host.clientHeight,.1,100),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(host.clientWidth,host.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.28;host.appendChild(renderer.domElement);
 const world=new THREE.Group();scene.add(world);const metal=new THREE.MeshPhysicalMaterial({color:0x071321,roughness:.26,metalness:.84,clearcoat:1}),cyan=new THREE.MeshStandardMaterial({color:0x54ceff,emissive:0x0b84cb,emissiveIntensity:2.2,roughness:.18,metalness:.42}),violet=new THREE.MeshStandardMaterial({color:0x7868ff,emissive:0x3b27ca,emissiveIntensity:2,roughness:.2}),glass=(c:number,o=.7)=>new THREE.MeshPhysicalMaterial({color:c,transparent:true,opacity:o,transmission:.32,roughness:.12,metalness:.24,emissive:c,emissiveIntensity:.14,clearcoat:1});
 const stations=[-9,-3,3,9];const bases:THREE.Group[]=[];stations.forEach((x,i)=>{const g=new THREE.Group(),base=new THREE.Mesh(new THREE.CylinderGeometry(2.45,2.7,.42,32),metal),rim=new THREE.Mesh(new THREE.TorusGeometry(2.38,.045,8,72),new THREE.MeshBasicMaterial({color:i%2?0x7564ff:0x42c8ff,transparent:true,opacity:.65}));base.position.y=.2;rim.rotation.x=Math.PI/2;rim.position.y=.44;g.add(base,rim);g.position.x=x;world.add(g);bases.push(g)});
 const radar=bases[0],mast=new THREE.Mesh(new THREE.CylinderGeometry(.08,.13,2.35,16),metal);mast.position.y=1.55;radar.add(mast);const dish=new THREE.Mesh(new THREE.SphereGeometry(1.08,28,18,0,Math.PI*2,0,.62),glass(0x45bdff,.58));dish.scale.y=.38;dish.rotation.z=-.55;dish.position.set(.22,2.72,0);radar.add(dish);const sensor=new THREE.Mesh(new THREE.SphereGeometry(.18,20,20),cyan);sensor.position.set(.76,3.04,0);radar.add(sensor);const signals:THREE.Mesh[]=[];for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(.52+i*.38,.025,8,52),new THREE.MeshBasicMaterial({color:0x5bd2ff,transparent:true,opacity:.55-i*.1}));ring.rotation.y=Math.PI/2;ring.rotation.z=-.55;ring.position.set(1.25+i*.32,3.35+i*.2,0);radar.add(ring);signals.push(ring)}
 const team=bases[1],table=new THREE.Mesh(new THREE.CylinderGeometry(1.18,1.18,.18,32),glass(0x244f82,.72));table.position.y=1.18;team.add(table);const plan=new THREE.Mesh(new THREE.BoxGeometry(1.25,.08,.82),glass(0x5a54ff,.8));plan.position.y=1.34;team.add(plan);const people:THREE.Group[]=[];for(let i=0;i<4;i++){const a=i*Math.PI/2+.25,g=new THREE.Group(),body=new THREE.Mesh(new THREE.CylinderGeometry(.18,.25,.62,16),i===0?violet:cyan),head=new THREE.Mesh(new THREE.SphereGeometry(.19,18,18),glass(i===0?0x8b7cff:0x68d4ff,.9));body.position.y=.62;head.position.y=1.08;g.add(body,head);g.position.set(Math.cos(a)*1.75,.45,Math.sin(a)*1.75);g.lookAt(0,.8,0);team.add(g);people.push(g)}
 const lab=bases[2],board=new THREE.Mesh(new THREE.BoxGeometry(2.35,.18,1.55),glass(0x1974a9,.58));board.position.y=1.08;lab.add(board);const modules:THREE.Mesh[]=[];[[-.7,0,.35],[0,0,.62],[.68,0,.44],[-.35,.48,.28],[.38,-.48,.3]].forEach((v,i)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(v[2],.24,v[2]),i===1?violet:cyan);m.position.set(v[0],1.28,v[1]);lab.add(m);modules.push(m)});const shell=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(2.65,2.35,2)),new THREE.LineBasicMaterial({color:0x64d1ff,transparent:true,opacity:.58}));shell.position.y=1.85;lab.add(shell);const gear=new THREE.Mesh(new THREE.TorusGeometry(.48,.14,10,28),metal);gear.position.set(0,2.33,0);gear.rotation.x=Math.PI/2;lab.add(gear);
 const result=bases[3],bars:THREE.Mesh[]=[];[.7,1.15,1.65].forEach((h,i)=>{const b=new THREE.Mesh(new THREE.BoxGeometry(.45,h,.55),i===2?violet:cyan);b.position.set(-.72+i*.68,.48+h/2,.25);result.add(b);bars.push(b)});const target=new THREE.Mesh(new THREE.TorusGeometry(.78,.08,10,48),glass(0x5bd2ff,.86));target.position.set(.2,2.72,0);result.add(target);const check=new THREE.Group();const c1=new THREE.Mesh(new THREE.BoxGeometry(.12,.62,.12),cyan),c2=new THREE.Mesh(new THREE.BoxGeometry(.12,1.15,.12),cyan);c1.rotation.z=-.72;c2.rotation.z=.72;c1.position.set(-.24,2.62,.03);c2.position.set(.25,2.82,.03);check.add(c1,c2);result.add(check);
 const route=new THREE.CatmullRomCurve3(stations.map(x=>new THREE.Vector3(x,.58,0)));const track=new THREE.Line(new THREE.BufferGeometry().setFromPoints(route.getPoints(180)),new THREE.LineBasicMaterial({color:0x287cb0,transparent:true,opacity:.5}));world.add(track);const pulse=new THREE.Mesh(new THREE.SphereGeometry(.15,16,16),new THREE.MeshBasicMaterial({color:0xe7f9ff}));pulse.add(new THREE.PointLight(0x54caff,12,4));world.add(pulse);stations.forEach(x=>{const n=new THREE.Mesh(new THREE.SphereGeometry(.1,12,12),cyan);n.position.set(x,.59,0);world.add(n)});
 scene.add(new THREE.HemisphereLight(0x5cbfff,0x01030a,1.15));const key=new THREE.PointLight(0x48b5ff,48,45);key.position.set(4,13,10);scene.add(key);const rim=new THREE.PointLight(0x705aff,42,40);rim.position.set(-10,7,-8);scene.add(rim);const floor=new THREE.Mesh(new THREE.PlaneGeometry(70,32),new THREE.MeshStandardMaterial({color:0x02050b,roughness:.38,metalness:.72}));floor.rotation.x=-Math.PI/2;floor.position.y=-.03;scene.add(floor);const grid=new THREE.GridHelper(60,60,0x163b63,0x091b2e);grid.position.y=.01;scene.add(grid);
 const camCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(-13,7,11),new THREE.Vector3(-5,5.4,10),new THREE.Vector3(2,4.2,9),new THREE.Vector3(7,6.8,10),new THREE.Vector3(13,8,12)]),lookCurve=new THREE.CatmullRomCurve3(stations.map(x=>new THREE.Vector3(x,1.45,0)));let mx=0,my=0,raf=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,pointer=(e:PointerEvent)=>{mx=e.clientX/innerWidth-.5;my=e.clientY/innerHeight-.5},resize=()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)};addEventListener('pointermove',pointer);addEventListener('resize',resize);
 const animate=()=>{const parent=host.closest('.village-journey') as HTMLElement,r=parent?.getBoundingClientRect(),travel=Math.max(1,(parent?.offsetHeight||innerHeight)-innerHeight),p=Math.max(0,Math.min(1,-(r?.top||0)/travel)),t=performance.now()*.001;camera.position.copy(camCurve.getPointAt(p));camera.position.x+=mx*.32;camera.position.y-=my*.2;camera.lookAt(lookCurve.getPointAt(p));pulse.position.copy(route.getPointAt(p));signals.forEach((s,i)=>{const q=(t*.55+i/3)%1;s.scale.setScalar(.65+q*.7);(s.material as THREE.MeshBasicMaterial).opacity=.6*(1-q)});people.forEach((g,i)=>g.position.y=.45+Math.sin(t*2+i)*.045);modules.forEach((m,i)=>{const active=Math.max(0,Math.min(1,(p-.43)*7-i*.07));m.position.y=1.28+(1-active)*(1.8+i*.16)});bars.forEach((b,i)=>{const active=Math.max(.03,Math.min(1,(p-.7)*6-i*.1));b.scale.y=active;b.position.y=.48+(b.geometry as THREE.BoxGeometry).parameters.height*active/2});target.rotation.z=reduced?0:t*.35;gear.rotation.z=reduced?0:t*.65;check.scale.setScalar(Math.max(.02,Math.min(1,(p-.78)*5)));renderer.render(scene,camera);raf=requestAnimationFrame(animate)};animate();return()=>{cancelAnimationFrame(raf);removeEventListener('pointermove',pointer);removeEventListener('resize',resize);renderer.dispose();host.removeChild(renderer.domElement)}},[]);
 return <div className="village-canvas" ref={mount} aria-label="رحلة ابتكار ثلاثية الأبعاد من رصد الاحتياج إلى قياس النتيجة" role="img"/>;
}
