'use client';
import { useEffect, useRef } from 'react';
import * as THREE from 'three';

export default function InnovationVillage(){
 const mount=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!mount.current)return;const host=mount.current;const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x020711,.026);const camera=new THREE.PerspectiveCamera(38,host.clientWidth/host.clientHeight,.1,100);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(host.clientWidth,host.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;host.appendChild(renderer.domElement);
 const product=new THREE.Group();scene.add(product);const dark=new THREE.MeshPhysicalMaterial({color:0x06101e,roughness:.24,metalness:.82,clearcoat:1});const cyan=new THREE.MeshStandardMaterial({color:0x52c8ff,emissive:0x138bd7,emissiveIntensity:2.4,roughness:.18,metalness:.35});const violet=new THREE.MeshStandardMaterial({color:0x7162ff,emissive:0x3e25cf,emissiveIntensity:2.1,roughness:.2});const glass=(c:number,o=.74)=>new THREE.MeshPhysicalMaterial({color:c,transparent:true,opacity:o,transmission:.3,roughness:.12,metalness:.28,emissive:c,emissiveIntensity:.17,clearcoat:1});
 const platform=(x:number,z:number,w:number,d:number)=>{const g=new THREE.Group();const a=new THREE.Mesh(new THREE.BoxGeometry(w,.45,d),dark);a.position.y=.18;g.add(a);const b=new THREE.Mesh(new THREE.BoxGeometry(w*.9,.1,d*.9),glass(0x184071,.52));b.position.y=.47;g.add(b);g.position.set(x,0,z);product.add(g);return g};
 const center=platform(0,0,5.2,5.2);const rings=[2.2,1.6,1.05];rings.forEach((r,i)=>{const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,.35,8),i===2?glass(0x45bdff,.83):dark);m.position.y=.65+i*.3;center.add(m)});const core=new THREE.Mesh(new THREE.IcosahedronGeometry(.7,2),glass(0x4ec9ff,.9));core.position.y=2.05;center.add(core);const coreWire=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.IcosahedronGeometry(.95,2)),new THREE.LineBasicMaterial({color:0x77d5ff,transparent:true,opacity:.78}));coreWire.position.copy(core.position);center.add(coreWire);
 const cubePad=platform(6,1.5,4.3,4.3);const shell=new THREE.Mesh(new THREE.BoxGeometry(2.6,2.6,2.6),glass(0x2f8dff,.58));shell.position.y=2;cubePad.add(shell);const inner=new THREE.Mesh(new THREE.BoxGeometry(1.55,1.55,1.55),glass(0x634cff,.88));inner.position.y=2;cubePad.add(inner);const cubeEdges=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(3,3,3)),new THREE.LineBasicMaterial({color:0x62c6ff,transparent:true,opacity:.72}));cubeEdges.position.y=2;cubePad.add(cubeEdges);
 const plantPad=platform(-6,-1.4,3.8,3.8);const seed=new THREE.Mesh(new THREE.SphereGeometry(.62,32,32),glass(0x7052ff,.88));seed.position.y=1.2;plantPad.add(seed);const stem=new THREE.Mesh(new THREE.CylinderGeometry(.055,.08,2.15,12),cyan);stem.position.y=2.25;plantPad.add(stem);const leafGeo=new THREE.SphereGeometry(.5,20,12);const leaf1=new THREE.Mesh(leafGeo,glass(0x4ecbff,.82));leaf1.scale.set(1.25,.22,.55);leaf1.rotation.z=.55;leaf1.position.set(.46,2.65,0);plantPad.add(leaf1);const leaf2=leaf1.clone();leaf2.rotation.z=-.55;leaf2.position.x=-.46;plantPad.add(leaf2);const globe=new THREE.Mesh(new THREE.SphereGeometry(1.6,18,12),new THREE.MeshBasicMaterial({wireframe:true,color:0x347fd0,transparent:true,opacity:.35}));globe.position.y=4.45;plantPad.add(globe);
 const dataGroup=new THREE.Group();dataGroup.position.set(-1.7,0,4.8);product.add(dataGroup);for(let i=0;i<11;i++){const size=.48+(i%3)*.18;const c=new THREE.Mesh(new THREE.BoxGeometry(size,size,size),i%4===0?violet:glass(0x3baaff,.77));const a=i*.92;c.position.set(Math.cos(a)*(1.8+(i%2)*.55),.7+(i%4)*.75,Math.sin(a)*(1.5+(i%2)*.45));dataGroup.add(c)}const dataRing=new THREE.Mesh(new THREE.TorusGeometry(2.2,.045,8,64),new THREE.MeshBasicMaterial({color:0x357fd0,transparent:true,opacity:.4}));dataRing.rotation.x=Math.PI/2;dataRing.position.y=.38;dataGroup.add(dataRing);
 const paths:THREE.CatmullRomCurve3[]=[];const addPath=(pts:THREE.Vector3[],color=0x42bcff)=>{const curve=new THREE.CatmullRomCurve3(pts);paths.push(curve);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(curve.getPoints(100)),new THREE.LineBasicMaterial({color,transparent:true,opacity:.55}));product.add(line);for(let j=0;j<3;j++){const l=line.clone();l.position.y=.035*(j+1);product.add(l)}return curve};addPath([new THREE.Vector3(6,.65,1.5),new THREE.Vector3(3.5,.8,2.1),new THREE.Vector3(1.8,.7,.7),new THREE.Vector3(0,1,0)]);addPath([new THREE.Vector3(0,1,0),new THREE.Vector3(-2,.7,-.2),new THREE.Vector3(-3.7,.9,-1),new THREE.Vector3(-6,.7,-1.4)],0x7564ff);addPath([new THREE.Vector3(0,1,0),new THREE.Vector3(-.7,.8,2.7),new THREE.Vector3(-1.7,.7,4.8)]);
 const pulse=new THREE.Mesh(new THREE.SphereGeometry(.16,16,16),new THREE.MeshBasicMaterial({color:0xd6f4ff}));const halo=new THREE.PointLight(0x55caff,10,4);pulse.add(halo);product.add(pulse);const nodes:THREE.Mesh[]=[];for(let i=0;i<18;i++){const n=new THREE.Mesh(new THREE.SphereGeometry(.055,8,8),cyan);const a=i/18*Math.PI*2;n.position.set(-6+Math.cos(a)*1.62,4.45+Math.sin(a)*1.62,-1.4);plantPad.add(n);nodes.push(n)}
 scene.add(new THREE.HemisphereLight(0x5cbfff,0x01030a,1.2));const key=new THREE.PointLight(0x46adff,55,38);key.position.set(8,12,9);scene.add(key);const rim=new THREE.PointLight(0x7257ff,46,34);rim.position.set(-9,7,-7);scene.add(rim);const floor=new THREE.Mesh(new THREE.PlaneGeometry(60,60),new THREE.MeshStandardMaterial({color:0x02050b,roughness:.35,metalness:.7}));floor.rotation.x=-Math.PI/2;floor.position.y=-.08;scene.add(floor);const grid=new THREE.GridHelper(40,40,0x163b63,0x0a1d33);grid.position.y=-.04;scene.add(grid);
 let mx=0,my=0,raf=0;const pointer=(e:PointerEvent)=>{mx=e.clientX/innerWidth-.5;my=e.clientY/innerHeight-.5};const resize=()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)};addEventListener('pointermove',pointer);addEventListener('resize',resize);
 const animate=()=>{const parent=host.closest('.village-journey') as HTMLElement;const r=parent?.getBoundingClientRect();const travel=Math.max(1,(parent?.offsetHeight||innerHeight)-innerHeight);const p=Math.max(0,Math.min(1,-(r?.top||0)/travel));const angle=.45+p*Math.PI*2.18+mx*.12;const radius=18-2*Math.sin(p*Math.PI);const commercialLift=p<.28?10+p*25:p<.58?17-(p-.28)*43:4+(p-.58)*20;camera.position.set(Math.cos(angle)*radius,commercialLift-my*.7,Math.sin(angle)*radius);camera.lookAt(0,1.25+(p>.3&&p<.65?1.1:0),0);const pathPhase=p*2.45;const pathIndex=Math.min(2,Math.floor(pathPhase));const t=Math.min(1,pathPhase-pathIndex);pulse.position.copy(paths[pathIndex].getPointAt(t));const activated=Math.max(0,(p-.48)/.34);nodes.forEach((n,i)=>{const on=activated*18>i;n.visible=on;n.scale.setScalar(on?1+.35*Math.sin(performance.now()*.006+i):.01)});core.rotation.y+=.005;coreWire.rotation.y-=.003;inner.rotation.y+=.0025;dataGroup.rotation.y+=.0015;globe.rotation.y+=.0015;renderer.render(scene,camera);raf=requestAnimationFrame(animate)};animate();return()=>{cancelAnimationFrame(raf);removeEventListener('pointermove',pointer);removeEventListener('resize',resize);renderer.dispose();host.removeChild(renderer.domElement)}},[]);
 return <div className="village-canvas" ref={mount} aria-hidden="true"/>;
}
