'use client';
import Image from 'next/image';
import { useEffect, useState } from 'react';
const nav=[['الأعمال','work'],['الخبرة','experience'],['الإنجازات','achievements'],['عني','about'],['تواصل','contact']];
const work=[
 {name:'SAFE ZONE',tag:'AI · CROWD SAFETY',image:'/projects/safe-zone.jpg',problem:'كيف نكتشف خطر الحشود مبكرًا ونوجّه الإخلاء بوضوح؟',built:'نظام يجمع الرؤية الحاسوبية وتحليل الكثافة والتنبيهات والتوجيه الصوتي في تجربة تشغيل واحدة.',role:'قيادة الفكرة والفريق · تصميم النظام · تكامل النموذج · التوثيق والعرض',tech:['Computer Vision','AI','CCTV Analytics','Real-time Dashboard'],result:'المركز الأول وطنيًا · ميدالية شرفية عالمية'},
 {name:'GRAVITYX',tag:'SPACE R&D',image:'/projects/gravityx.jpg',problem:'كيف نبني منصة بحثية مرنة لتجارب وتقنيات الفضاء؟',built:'منصة للنمذجة والتجارب والقياس عن بُعد وتكامل الحساسات والتطوير الهندسي.',role:'قيادة البحث والتطوير · تصميم المنتج · النمذجة · الملف البحثي',tech:['ESP32','Raspberry Pi','Telemetry','3D Printing'],result:'الثالث وطنيًا · جائزة أفضل أداء عالميًا · طلب براءة قيد الفحص'},
 {name:'NEXT STABLE',tag:'IOT · EQUINE CARE',image:'/projects/next-stable.jpg',problem:'كيف تصبح رعاية الخيل وسلامة الفارس أكثر ذكاءً واستدامة؟',built:'منظومة تدمج المؤشرات الحيوية والحساسات والأتمتة والروبوتات والطاقة الشمسية.',role:'تصميم مفهوم النظام · النمذجة · البرمجة · قيادة الفريق',tech:['Arduino','ESP32','IoT Sensors','VEX Robotics'],result:'الأول في الرياض · الثالث على مستوى المملكة'},
 {name:'SUHAIL · LIFE SIGNAL',tag:'EMERGENCY CONNECTIVITY',image:'/projects/suhail.jpg',problem:'كيف تستمر الاتصالات والخدمات الأساسية وقت الانقطاع؟',built:'جهاز تفاعلي وشبكة اتصال مؤقتة تجمع الصوت والحساسات وLoRa لتنفيذ وظائف مباشرة.',role:'قيادة الحل · تكامل العتاد والبرمجيات · تجربة الاستخدام',tech:['LoRa','ESP32','Raspberry Pi','Sensors'],result:'المركز الثاني · WRO السعودية 2024'},
 {name:'SAHM',tag:'AI PRODUCTIVITY',image:'/projects/sahm.jpg',problem:'كيف تتحول الأفكار الصوتية اليومية إلى خطوات قابلة للتنفيذ؟',built:'مساعد شخصي ينظم الملاحظات إلى مهام ومواعيد وخطط ويتعلم من نمط المستخدم.',role:'تصميم المنتج · هندسة التدفق · تطوير النموذج',tech:['AI Agents','Voice Processing','Python','SQLite'],result:'منتج رقمي قيد التطوير ضمن نوسج'}];
const experience=[{date:'2023 — الآن',role:'مدربة روبوتيك وابتكار',org:'مدارس ابن خلدون · الرياض',points:['قيادة أربع فرق خلال دورة الابتكار من المشكلة إلى العرض النهائي.','إرشاد تقني في البرمجة والروبوتات وتكامل الأنظمة.','تحويل العمل الطلابي إلى نتائج وطنية وعالمية موثقة.']},{date:'2022 — 2023',role:'معلمة حاسب آلي',org:'مدارس الفنار الأهلية · الرياض',points:['تصميم تجارب تعلم تطبيقية للمرحلة المتوسطة.','دمج البرمجة والروبوتات والمهارات الرقمية في مشروعات قابلة للتقييم.']},{date:'2022',role:'مطوّرة Full-Stack · تدريب',org:'Afrilearn Academy / الأكاديمية السعودية الرقمية',points:['تطوير تطبيقات MERN وواجهات متجاوبة.','ربط REST APIs والعمل ضمن فرق تقنية ثنائية اللغة.']}];
const awards=[['01','المركز الأول في السعودية','Codeavour · 2024','Safe Zone'],['02','ميدالية شرفية عالمية','Codeavour · 2024','Safe Zone'],['03','المركز الثاني في السعودية','WRO · 2024','Life Signal'],['04','المركز الأول في الرياض والثالث وطنيًا','2024','Next Stable'],['05','المركز الثالث في السعودية','WRO · 2025','GravityX'],['06','جائزة أفضل أداء عالميًا','Global Robotics Challenge · 2025','GravityX']];
const skills=[['BUILD',['Product Prototyping','MVP Development','Web Products','Design Thinking','Feasibility Studies']],['AI & AUTOMATION',['AI Workflows','AI Agents','Computer Vision','Voice Processing','Automation','Python']],['PHYSICAL COMPUTING',['ESP32','Arduino','Raspberry Pi','IoT','LoRa','Robotics','Sensors']],['LEADERSHIP',['Innovation Programs','Technical Training','Competition Teams','Project Leadership','Stakeholder Management']]];
export default function Home(){const [menu,setMenu]=useState(false),[active,setActive]=useState('work');useEffect(()=>{const r=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle('is-visible',e.isIntersecting)),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>r.observe(x));const s=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)setActive(e.target.id)}),{rootMargin:'-35% 0px -55%'});nav.forEach(([,id])=>{const el=document.getElementById(id);if(el)s.observe(el)});return()=>{r.disconnect();s.disconnect()}},[]);return <main>
<header className="site-header"><a className="brand" href="#top" aria-label="العودة إلى بداية الصفحة"><b>أفنان أحمد الدحيم</b><span>TECHNOLOGY BUILDER · INNOVATION SPECIALIST</span></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-controls="main-nav">{menu?'إغلاق':'القائمة'}</button><nav id="main-nav" className={menu?'open':''} aria-label="التنقل الرئيسي">{nav.map(([label,id])=><a key={id} className={active===id?'active':''} href={`#${id}`} onClick={()=>setMenu(false)}>{label}</a>)}<a className="nav-contact" href="mailto:afnan.aldohime@gmail.com">ابدأ محادثة</a></nav></header>
<section className="hero" id="top"><div className="hero-grid" aria-hidden="true"/><div className="hero-copy"><p className="eyebrow"><i/>مهندسة ابتكار ومنتجات تقنية · الرياض</p><h1>أحوّل الأفكار إلى<br/><span>نماذج ومنتجات تقنية</span><br/>قابلة للتجربة.</h1><p className="hero-summary">أعمل عند نقطة التقاء تصميم المنتجات والذكاء الاصطناعي والأتمتة والروبوتات وإنترنت الأشياء—وأقود الفرق من السؤال الأول حتى نموذج يعمل ودليل يمكن قياسه.</p><div className="hero-actions"><a className="button primary" href="#work">استكشف أعمالي <span>←</span></a><a className="button secondary" href="mailto:afnan.aldohime@gmail.com">تواصل معي</a></div></div><aside className="hero-profile"><span>AFNAN AHMAD</span><div className="profile-mark">A</div><dl><div><dt>التركيز</dt><dd>Product · AI · IoT</dd></div><div><dt>الدور</dt><dd>Founder &amp; CTO — Nawwsaj</dd></div><div><dt>التوفر</dt><dd><i/>فرص وتعاونات مختارة</dd></div></dl></aside></section>
<section className="proof" aria-label="ملخص المصداقية"><div><strong>3+</strong><span>سنوات في التدريب التقني والابتكار</span></div><div><strong>06</strong><span>نتائج وطنية وعالمية</span></div><div><strong>R&amp;D</strong><span>بحث وتطوير ونماذج أولية</span></div><div><strong>AI + IoT</strong><span>برمجيات وأنظمة مدمجة</span></div><div><strong>CTO</strong><span>مؤسسة نوسج</span></div></section>
<section className="section work" id="work"><SectionHead no="01 / SELECTED WORK" label="الأعمال المختارة" title={<>مشروعات تحوّل<br/>التحديات إلى <em>أنظمة تعمل.</em></>}/><div className="case-list">{work.map((p,i)=><article className={`case reveal ${i===0?'featured':''}`} key={p.name}><div className="case-media"><Image src={p.image} alt={`تصور لمشروع ${p.name}`} fill sizes={i===0?'(max-width: 768px) 100vw, 55vw':'(max-width: 768px) 100vw, 40vw'}/><span>{p.tag}</span></div><div className="case-copy"><div className="case-index">0{i+1}</div><h3>{p.name}</h3><p className="case-problem">{p.problem}</p><dl><div><dt>ما الذي بنيته</dt><dd>{p.built}</dd></div><div><dt>دوري</dt><dd>{p.role}</dd></div></dl><ul>{p.tech.map(t=><li key={t}>{t}</li>)}</ul><strong>{p.result}</strong></div></article>)}</div></section>
<section className="section experience" id="experience"><SectionHead no="02 / EXPERIENCE" label="الخبرة المهنية" title={<>قيادة تقنية.<br/><em>وتعلّم يتحول إلى إنجاز.</em></>}/><div className="timeline">{experience.map((e,i)=><article className="reveal" key={e.role}><span>0{i+1}</span><time>{e.date}</time><div><p>{e.org}</p><h3>{e.role}</h3><ul>{e.points.map(x=><li key={x}>{x}</li>)}</ul></div></article>)}</div></section>
<section className="section achievements" id="achievements"><SectionHead no="03 / RECOGNITION" label="المنافسات والإنجازات" title={<>دليل خارجي على<br/><em>جودة القيادة والتنفيذ.</em></>}/><div className="award-grid">{awards.map(a=><article className="reveal" key={a[0]}><span>{a[0]}</span><p>{a[3]}</p><h3>{a[1]}</h3><small>{a[2]}</small></article>)}</div></section>
<section className="section capabilities" id="skills"><SectionHead no="04 / CAPABILITIES" label="المهارات والقدرات" title={<>أجمع بين المنتج<br/><em>والتقنية والقيادة.</em></>}/><div className="capability-grid">{skills.map((s,i)=><article className="reveal" key={s[0] as string}><span>0{i+1}</span><h3>{s[0] as string}</h3><ul>{(s[1] as string[]).map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></section>
<section className="section about" id="about"><div className="about-title reveal"><span>05 / ABOUT</span><p>عني</p><h2>أبني من المشكلة<br/><em>إلى الخارج.</em></h2></div><div className="about-copy reveal"><p>أفكر في التقنية كوسيلة لتقليل المسافة بين احتياج حقيقي ونتيجة نافعة. لذلك أبدأ بالسؤال والسياق، ثم أنتقل إلى التصميم والنموذج والاختبار.</p><p>أستمتع بالمشكلات التي تحتاج جمع تخصصات مختلفة: تجربة المستخدم، البرمجيات، العتاد، الذكاء الاصطناعي، والبحث—خصوصًا عندما يتطلب الحل قيادة فريق وتحويل الغموض إلى خطة.</p><div className="credentials"><div><span>التعليم</span><b>ماجستير مهني في إدارة الأعمال</b><small>إدارة · تخطيط · اتخاذ قرار</small></div><div><span>الأساس التقني</span><b>بكالوريوس علوم الحاسب</b><small>جامعة شقراء · 2016</small></div><div><span>البحث</span><b>GravityX</b><small>طلب براءة قيد الفحص · ORCID مسجل</small></div></div></div></section>
<section className="contact" id="contact"><p className="reveal">06 / LET’S BUILD</p><div className="reveal"><h2>عندك فكرة تحتاج<br/>تتحول إلى <em>شيء يعمل؟</em></h2><a href="mailto:afnan.aldohime@gmail.com">ابدأ المحادثة <span>↗</span></a></div><footer><span>أفنان أحمد الدحيم · الرياض</span><nav aria-label="روابط التواصل"><a href="mailto:afnan.aldohime@gmail.com">Email</a><a href="https://linkedin.com/in/nnonni1">LinkedIn</a><a href="https://github.com/nnonni1">GitHub</a><a href="https://nawwsaj.com">Nawwsaj</a></nav><span>© 2026</span></footer></section></main>}
function SectionHead({no,label,title}:{no:string,label:string,title:React.ReactNode}){return <header className="section-head reveal"><div><span>{no}</span><p>{label}</p></div><h2>{title}</h2></header>}
