'use client';
import { useEffect, useState } from 'react';

const scenes=[
 {id:'origin',no:'01',eyebrow:'من الاحتياج إلى النموذج',title:'أحوّل التحدي إلى نظام قابل للاختبار.',text:'أبدأ من المشكلة الحقيقية، أفككها، ثم أنسج البحث والتقنية والفريق في نموذج يعمل.',image:'/scene-origin.png'},
 {id:'system',no:'02',eyebrow:'منهج قيادة متصل',title:'كل قرار يرتبط بالنتيجة.',text:'البحث، الجدوى، الأنظمة المدمجة، الذكاء الاصطناعي والعرض—مسار واحد تقوده رؤية واضحة.',image:'/scene-system.png'},
 {id:'worlds',no:'03',eyebrow:'مشروعات تصنع أثرًا',title:'ثلاثة عوالم. منهج واحد.',text:'اتصالات طوارئ أكثر مرونة، مدن أكثر أمانًا، وبحث فضائي ينتقل من المحاكاة إلى الملكية الفكرية.',image:'/scene-worlds.png'}
];
const projects=[['LIFE SIGNAL','اتصالات الطوارئ','المركز الثاني وطنيًا','شبكة LoRa وArduino وVEX تنشر نقاط اتصال مؤقتة عند انقطاع الشبكات.'],['SAFEZONE','السلامة الذكية','الأول وطنيًا · ميدالية عالمية','تصنيف صور بالذكاء الاصطناعي وحساسات لهب واهتزاز ومساعد صوتي.'],['GRAVITYX','تقنيات الفضاء','الثالث في WRO · جائزة عالمية','محطة فضائية بجاذبية اصطناعية مرتبطة بطلب براءة سعودي.'],['NAWWSAJ OS','أنظمة الابتكار','قيد التطوير','ربط وكلاء الذكاء الاصطناعي بالأجهزة وسير العمل داخل معامل الابتكار.']];
const experience=[['2023—2026','مدربة روبوتيك وابتكار','مدارس ابن خلدون','قدت أربع فرق عبر دورة الابتكار كاملة: المشكلة، البحث، النموذج، الجدوى والعرض.'],['2022—2023','معلمة حاسب آلي','مدارس الفنار الأهلية','دمجت البرمجة والروبوتات والمشروعات التطبيقية في تجربة التعلم.'],['2022','مطورة Full-Stack','Afrilearn Academy','طورت تطبيقات MERN متكاملة ضمن فرق عمل ثنائية اللغة.']];
const tools=['ESP32','Arduino','Raspberry Pi','VEX','LoRa','Python','JavaScript','React','Node.js','Machine Learning','WebSocket','REST APIs'];

export default function Home(){
 const [progress,setProgress]=useState(0);
 const [heroFrame,setHeroFrame]=useState(0);
 useEffect(()=>{const tick=()=>{const max=document.documentElement.scrollHeight-innerHeight;setProgress(max?scrollY/max:0);const hero=document.querySelector<HTMLElement>('.intro');if(hero){const r=hero.getBoundingClientRect();const travel=Math.max(1,r.height-innerHeight);const p=Math.max(0,Math.min(1,-r.top/travel));setHeroFrame(Math.min(5,Math.floor(p*6)))}document.querySelectorAll<HTMLElement>('.world-scene').forEach(el=>{const r=el.getBoundingClientRect();const p=Math.max(0,Math.min(1,(innerHeight-r.top)/(r.height+innerHeight)));el.style.setProperty('--p',p.toFixed(4))})};const io=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle('in',e.isIntersecting)),{threshold:.14});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));tick();addEventListener('scroll',tick,{passive:true});addEventListener('resize',tick);return()=>{removeEventListener('scroll',tick);removeEventListener('resize',tick);io.disconnect()}},[]);
 return <main>
  <div className="progress" style={{transform:`scaleX(${progress})`}}/>
  <nav className="nav"><a className="logo" href="#top"><b>أفنان الدحيم</b><span>INNOVATION SYSTEMS</span></a><div><a href="#journey">الرحلة</a><a href="#projects">المشروعات</a><a href="#experience">الخبرة</a></div><a className="contact-chip" href="mailto:afnan.aldohime@gmail.com">تواصل معي</a></nav>
  <header className="intro" id="top"><div className="intro-sticky"><div className="intro-aura"/><div className="intro-copy reveal"><p className="overline"><i/> قائدة ابتكار اجتماعي وتطوير برامج</p><h1>أبني أنظمة<br/><span>تحوّل الفكرة</span><br/>إلى أثر.</h1><p>مرّري للأسفل وشاهدي الفكرة تستيقظ، تعبر النظام، ثم تبني شبكة أثر متصلة.</p><a href="#journey">تابعي الرحلة <b>↓</b></a></div><div className="frame-sequence" role="img" aria-label="تسلسل متحرك يوضح انتقال الضوء من المكعب إلى البذرة وتكوين شبكة الابتكار">{Array.from({length:6}).map((_,i)=><img key={i} className={i===heroFrame?'active':''} src={`/origin-frame-${i}.png`} alt="" loading={i<2?'eager':'lazy'}/>)}</div><div className="frame-meter"><span>{String(heroFrame+1).padStart(2,'0')} / 06</span><i><b style={{transform:`scaleX(${(heroFrame+1)/6})`}}/></i><small>{['سكون','استيقاظ','انتقال','تكوين','نمو','منظومة'][heroFrame]}</small></div><div className="scroll-hint"><span>مرّري لتشغيل المشهد</span><i/></div></div></header>
  <section className="world" id="journey">{scenes.map((s,i)=><article className="world-scene" key={s.id}><div className="scene-sticky"><div className="scene-grid"/><img src={s.image} alt=""/><div className="scene-copy"><span className="scene-no">{s.no} / 03</span><p>{s.eyebrow}</p><h2>{s.title}</h2><div className="scene-line"><i/><span>{s.text}</span></div></div><div className="scene-index">{String(i+1).padStart(2,'0')}</div></div></article>)}</section>
  <section className="impact"><div className="section-label reveal"><span>04</span><p>الأثر بالأرقام</p></div><h2 className="reveal">حين يصبح المنهج<br/><span>نتائج موثّقة.</span></h2><div className="numbers"><article className="reveal"><strong>04</strong><p>فرق قُدت رحلتها كاملة</p></article><article className="reveal"><strong>05</strong><p>نتائج وطنية وعالمية</p></article><article className="reveal"><strong>03</strong><p>مراكز وطنية متقدمة</p></article><article className="reveal"><strong>01</strong><p>طلب براءة اختراع سعودي</p></article></div></section>
  <section className="projects" id="projects"><div className="section-label reveal"><span>05</span><p>مشروعات مختارة</p></div><div className="projects-head reveal"><h2>حلول تبدأ<br/>من الواقع.</h2><p>كل مشروع هنا لم يبدأ بتقنية، بل بسؤال: كيف نجعل حياة الناس أكثر أمانًا ومرونة وقدرة؟</p></div><div className="project-grid">{projects.map((p,i)=><article className="project reveal" key={p[0]}><div><span>0{i+1}</span><small>{p[1]}</small></div><h3>{p[0]}</h3><p>{p[3]}</p><b>{p[2]}</b></article>)}</div></section>
  <section className="experience" id="experience"><div className="exp-title reveal"><div className="section-label"><span>06</span><p>الخبرة</p></div><h2>قيادة الفكرة.<br/><span>وإنجازها.</span></h2></div><div className="exp-list">{experience.map((e,i)=><article className="reveal" key={e[1]}><span>0{i+1}</span><time>{e[0]}</time><div><h3>{e[1]}</h3><b>{e[2]}</b><p>{e[3]}</p></div></article>)}</div></section>
  <section className="toolkit"><div className="toolkit-core"><span>NAWWSAJ</span><b>OS</b></div><div className="toolkit-copy reveal"><div className="section-label"><span>07</span><p>القدرات التقنية</p></div><h2>التقنية<br/>حين تخدم الفكرة.</h2><p>من الأنظمة المدمجة وإنترنت الأشياء إلى الذكاء الاصطناعي وتطبيقات الويب.</p></div><div className="tool-cloud">{tools.map((t,i)=><span key={t} style={{'--i':i} as React.CSSProperties}>{t}</span>)}</div></section>
  <section className="education"><div className="section-label reveal"><span>08</span><p>التعليم والتطوير</p></div><div className="edu-grid"><article className="reveal"><small>الإدارة</small><h3>ماجستير مهني<br/>في إدارة الأعمال</h3><p>ربط الحلول التقنية بالقيمة التشغيلية والجدوى واتخاذ القرار.</p></article><article className="reveal"><small>التقنية</small><h3>بكالوريوس<br/>علوم الحاسب</h3><p>جامعة شقراء · الخوارزميات، قواعد البيانات، الشبكات وهندسة البرمجيات.</p></article></div></section>
  <footer><div><p>المشهد التالي يبدأ بسؤال.</p><h2>ما الأثر الذي<br/><span>سنبنيه معًا؟</span></h2></div><div className="links"><a href="mailto:afnan.aldohime@gmail.com">afnan.aldohime@gmail.com ↗</a><a href="tel:+966509597116">+966 50 959 7116 ↗</a><a href="https://nawwsaj.com">nawwsaj.com ↗</a><a href="https://linkedin.com/in/nnonni1">LinkedIn ↗</a></div><div className="footnote"><span>أفنان أحمد الدحيم</span><span>الرياض، المملكة العربية السعودية · 2026</span></div></footer>
 </main>
}
