'use client';
import { useEffect, useState } from 'react';

const metrics=[['04','فرق قُدت رحلتها كاملة'],['05','نتائج وطنية وعالمية'],['03','مراكز وطنية متقدمة'],['01','طلب براءة اختراع سعودي']];
const projects=[
 {year:'2024',name:'LIFE SIGNAL',tag:'اتصالات الطوارئ',result:'المركز الثاني وطنيًا',text:'شبكة LoRa وArduino وVEX تنشر نقاط اتصال مؤقتة عندما تنقطع الاتصالات في الكوارث.',tone:'acid',icon:'⌁'},
 {year:'2024',name:'SAFEZONE',tag:'سلامة الحشود',result:'الأول وطنيًا + ميدالية عالمية',text:'تصنيف صور بالذكاء الاصطناعي، حساسات لهب واهتزاز، ومساعد صوتي ضمن حل سلامة متكامل.',tone:'coral',icon:'◉'},
 {year:'2025',name:'GRAVITYX',tag:'تقنيات الفضاء',result:'الثالث في WRO + جائزة عالمية',text:'محطة فضائية تولّد جاذبية اصطناعية؛ من المحاكاة والبحث إلى طلب براءة سعودي.',tone:'blue',icon:'⊕'},
 {year:'NOW',name:'NAWWSAJ OS',tag:'أنظمة الابتكار',result:'قيد التطوير',text:'نظام يربط وكلاء الذكاء الاصطناعي بالأجهزة وسير العمل داخل المعامل لتسريع الاختبار.',tone:'paper',icon:'⌘'}
];
const experience=[['2023—2026','مدربة روبوتيك وابتكار','مدارس ابن خلدون، الرياض','قيادة أربع فرق من اكتشاف المشكلة إلى النموذج والعرض، مع إدارة التكامل التقني والجدوى والمنافسات.'],['2022—2023','معلمة حاسب آلي','مدارس الفنار الأهلية، الرياض','دمج البرمجة والروبوتات والمشروعات التطبيقية في تجربة تعلم عملية.'],['2022','مطورة Full-Stack','Afrilearn Academy','تطبيقات MERN متكاملة، واجهات متجاوبة، وربط REST APIs ضمن فرق ثنائية اللغة.']];
const tools=['ESP32','ARDUINO','RASPBERRY PI','VEX','LORA','PYTHON','JAVASCRIPT','REACT','NODE.JS','MACHINE LEARNING','WEBSOCKET','REST APIs'];

function Network(){return <div className="network" aria-hidden="true">{Array.from({length:14}).map((_,i)=><span key={i} className={`node node-${i+1}`}/>)}<span className="core">A</span><span className="orbit orbit-one"/><span className="orbit orbit-two"/><span className="orbit orbit-three"/></div>}
function Cube(){return <div className="cube-wrap" aria-hidden="true"><div className="cube"><span className="front">فكرة</span><span className="back">أثر</span><span className="right">تقنية</span><span className="left">فريق</span><span className="top">بحث</span><span className="bottom">نتيجة</span></div></div>}

export default function Home(){
 const [progress,setProgress]=useState(0);
 useEffect(()=>{const onScroll=()=>{const max=document.documentElement.scrollHeight-innerHeight;setProgress(max>0?scrollY/max:0);document.documentElement.style.setProperty('--scroll',String(scrollY))};const observer=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle('visible',e.isIntersecting)),{threshold:.16});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));onScroll();addEventListener('scroll',onScroll,{passive:true});return()=>{removeEventListener('scroll',onScroll);observer.disconnect()}},[]);
 return <main>
  <div className="progress" style={{transform:`scaleX(${progress})`}}/>
  <nav className="topbar" aria-label="التنقل الرئيسي"><a className="brand" href="#top"><span>نَسْج</span><small>NAWWSAJ / 01</small></a><div className="nav-links"><a href="#impact">الأثر</a><a href="#work">العمل</a><a href="#journey">الرحلة</a><a href="#contact">تواصل</a></div></nav>
  <section className="hero" id="top"><div className="hero-grid"/><Network/><div className="hero-copy"><p className="kicker"><span/> قائدة ابتكار اجتماعي وتطوير برامج</p><h1>أحوّل التحديات<br/>إلى <em>أنظمة أثر.</em></h1><p className="hero-lede">من الاحتياج المجتمعي إلى نموذج أولي قابل للاختبار—أقود الفكرة، التقنية، والفريق حتى النتيجة.</p><div className="hero-actions"><a className="button primary" href="#impact">استكشف الأثر <b>↓</b></a><a className="button ghost" href="mailto:afnan.aldohime@gmail.com">ابدأ مشروعًا معي</a></div></div><div className="hero-index"><span>AFNAN</span><span>ALDUHAIM</span></div><div className="scroll-label"><span>SCROLL TO EXPLORE</span><i/></div></section>
  <section className="impact" id="impact"><div className="impact-head reveal"><span className="section-no">02 / IMPACT</span><h2>الأرقام ليست نهاية القصة.<br/><em>هي دليل أن المنهج يعمل.</em></h2></div><div className="metrics">{metrics.map(([n,l],i)=><article className="metric reveal" key={l}><span className="metric-index">0{i+1}</span><strong>{n}</strong><p>{l}</p></article>)}</div></section>
  <section className="method" id="method"><div className="method-sticky"><span className="section-no">03 / METHOD</span><Cube/><div className="method-copy reveal"><p className="kicker"><span/> منهج متعدد التخصصات</p><h2>لا أبني نموذجًا فقط.<br/><em>أبني منظومة تنجح.</em></h2><p>أربط البحث، إدارة الأعمال، التقنية والعرض في مسار واحد. كل وجه من المكعب قرار؛ وكل قرار يخدم نتيجة قابلة للقياس.</p></div></div></section>
  <section className="work" id="work"><header className="work-head reveal"><span className="section-no">04 / SELECTED BUILDS</span><h2>مشروعات<br/><em>تعمل في الواقع.</em></h2></header><div className="project-list">{projects.map((p,i)=><article className={`project-card ${p.tone} reveal`} key={p.name}><div className="project-meta"><span>0{i+1}</span><span>{p.year}</span></div><div className="project-icon">{p.icon}</div><div><p className="project-tag">{p.tag}</p><h3>{p.name}</h3><p className="project-text">{p.text}</p></div><strong>{p.result}</strong></article>)}</div></section>
  <section className="journey" id="journey"><div className="journey-title reveal"><span className="section-no">05 / EXPERIENCE</span><h2>خبرة في<br/><em>القيادة والتنفيذ.</em></h2></div><div className="timeline">{experience.map(([date,role,place,text],i)=><article className="timeline-item reveal" key={role}><span className="timeline-no">0{i+1}</span><time>{date}</time><div><h3>{role}</h3><p className="place">{place}</p><p>{text}</p></div></article>)}</div></section>
  <section className="toolkit"><div className="marquee" aria-hidden="true"><div>{[...tools,...tools].map((t,i)=><span key={i}>{t}<b>✦</b></span>)}</div></div><div className="toolkit-copy reveal"><span className="section-no">06 / TOOLKIT</span><h2>تقنية تخدم الفكرة.<br/><em>وليست العكس.</em></h2><p>من الأنظمة المدمجة وإنترنت الأشياء إلى الذكاء الاصطناعي وتطبيقات الويب.</p></div></section>
  <section className="education"><span className="section-no">07 / EDUCATION</span><div className="edu-grid"><article className="reveal"><small>الإدارة</small><h3>ماجستير مهني<br/>في إدارة الأعمال</h3><p>التخطيط، اتخاذ القرار، وربط الحلول التقنية بالقيمة التشغيلية والجدوى.</p></article><article className="reveal"><small>التقنية</small><h3>بكالوريوس<br/>علوم الحاسب</h3><p>جامعة شقراء · الخوارزميات، قواعد البيانات، الشبكات وهندسة البرمجيات.</p></article></div></section>
  <footer id="contact"><div className="contact-grid"><div><span className="section-no">08 / NEXT IMPACT</span><h2>لنبنِ الأثر<br/><em>التالي معًا.</em></h2></div><div className="contact-links"><a href="mailto:afnan.aldohime@gmail.com">afnan.aldohime@gmail.com ↗</a><a href="tel:+966509597116">+966 50 959 7116 ↗</a><a href="https://nawwsaj.com">nawwsaj.com ↗</a><a href="https://linkedin.com/in/nnonni1">LinkedIn ↗</a></div></div><div className="footer-base"><span>أفنان أحمد الدحيم</span><span>RIYADH · SAUDI ARABIA · 2026</span></div></footer>
 </main>
}
